# Generated by Django 4.1.3 on 2022-11-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userauth_groups_userauth_is_active_userauth_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
