# Generated by Django 4.1.3 on 2022-11-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userauth_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
