# Generated by Django 4.1.3 on 2022-11-23 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_countries_id_alter_userauth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.countries'),
        ),
    ]
