# Generated by Django 3.2.15 on 2022-12-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userauth_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='photo',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
    ]
