# Generated by Django 3.2.15 on 2022-12-04 03:08

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userauth_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
