CREATE USER postgres WITH PASSWORD 'tuXL3XSF8O7tsGrcGHoMos4tVNtL3tnrRshSCZokGnIfk4ArDyzaa297k2WgQPSL';
CREATE DATABASE template;
GRANT ALL PRIVILEGES ON DATABASE template TO postgres;
ALTER USER postgres SUPERUSER;